# Copyright 2020 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

# docs/src/orchid/resources/config.yml
site:
  about:
    siteName: Captive Web View
    siteDescription: Library for an Android WebView or iOS WKWebView that is captive in the application.

#theme:
#  menu:
#    - type: 'separator'
#      title: 'Reference Documentation'
#    - type: 'kotlindocPackages'
#    - type: 'kotlindocClasses'

theme:
  primaryColor: '#DE9149'
  legacySearch: false
  social:
    github: 'vmware/captive-web-view'
  metaComponents:
    - type: 'orchidSearch'
  menu:
#    - type: 'separator'
#      title: 'Wiki'
#    - type: 'wiki'
#    - type: 'page'
#      itemId: 'Changelog'
    - type: 'separator'
      title: 'API Docs'
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'classes'
      asSubmenu: true
      submenuTitle: 'Classes'
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'packages'
      asSubmenu: true
      submenuTitle: 'Packages'

Editorial:
  primaryColor: '#DE9149'

BsDoc:
  primaryColor: '#DE9149'

kotlindoc:
  sourceDirs:
    - '../../../../captivewebview/src/main/java'
  pages:
    menu:
      - type: 'sourcedocPageLinks'
        moduleType: 'kotlindoc'
        itemTitleType: 'SIGNATURE'
        includeItems: true
#  args:
#    - '-links'
#    - 'https://developer.android.com/reference/^https://developer.android.com/reference/package-list^^'
   # - '-rubbishy'
#   - 'https://developer.android.com/reference/^https://developer.android.com/reference/kotlin/android/content/package-list^'

# //  externalDocumentationLink {
# //    url = new URL("https://developer.android.com/reference/")
# //    packageListUrl =
# //        new URL("https://developer.android.com/reference/android/support/package-list")
# //  }

# //  -links - external documentation links in format url^packageListUrl^^url2...
